<?php 
/**
	Admin Page Framework v3.8.20 by Michael Uno 
	Generated by PHP Class Files Script Generator <https://github.com/michaeluno/PHP-Class-Files-Script-Generator>
	<http://en.michaeluno.jp/wicfr>
	Copyright (c) 2013-2019, Michael Uno; Licensed under MIT <http://opensource.org/licenses/MIT> */
class AdminPageFramework_FieldType__nested extends AdminPageFramework_FieldType {
    public $aFieldTypeSlugs = array('_nested');
    protected $aDefaultKeys = array();
    protected function getStyles() {
        return ".wicfr-fieldset > .wicfr-fields > .wicfr-field.with-nested-fields > .wicfr-fieldset.multiple-nesting {margin-left: 2em;}.wicfr-fieldset > .wicfr-fields > .wicfr-field.with-nested-fields > .wicfr-fieldset {margin-bottom: 1em;}.with-nested-fields > .wicfr-fieldset.child-fieldset > .wicfr-child-field-title {display: inline-block;padding: 0 0 0.4em 0;}.wicfr-fieldset.child-fieldset > label.wicfr-child-field-title {display: table-row; white-space: nowrap;}";
    }
    protected function getField($aField) {
        $_oCallerForm = $aField['_caller_object'];
        $_aInlineMixedOutput = array();
        foreach ($this->getAsArray($aField['content']) as $_aChildFieldset) {
            if (is_scalar($_aChildFieldset)) {
                continue;
            }
            if (!$this->isNormalPlacement($_aChildFieldset)) {
                continue;
            }
            $_aChildFieldset = $this->getFieldsetReformattedBySubFieldIndex($_aChildFieldset, ( integer )$aField['_index'], $aField['_is_multiple_fields'], $aField);
            $_oFieldset = new AdminPageFramework_Form_View___Fieldset($_aChildFieldset, $_oCallerForm->aSavedData, $_oCallerForm->getFieldErrors(), $_oCallerForm->aFieldTypeDefinitions, $_oCallerForm->oMsg, $_oCallerForm->aCallbacks);
            $_aInlineMixedOutput[] = $_oFieldset->get();
        }
        return implode('', $_aInlineMixedOutput);
    }
    }
    class AdminPageFramework_FieldType_inline_mixed extends AdminPageFramework_FieldType__nested {
        public $aFieldTypeSlugs = array('inline_mixed');
        protected $aDefaultKeys = array('label_min_width' => '', 'show_debug_info' => false,);
        protected function getStyles() {
            return ".wicfr-field-inline_mixed {width: 98%;}.wicfr-field-inline_mixed > fieldset {display: inline-block;overflow-x: visible;padding-right: 0.4em;}.wicfr-field-inline_mixed > fieldset > .wicfr-fields{display: inline;width: auto;table-layout: auto;margin: 0;padding: 0;vertical-align: middle;white-space: nowrap;}.wicfr-field-inline_mixed > fieldset > .wicfr-fields > .wicfr-field {float: none;clear: none;width: 100%;display: inline-block;margin-right: auto;vertical-align: middle; }.with-mixed-fields > fieldset > label {width: auto;padding: 0;}.wicfr-field-inline_mixed > fieldset > .wicfr-fields > .wicfr-field .wicfr-input-label-string {padding: 0;}.wicfr-field-inline_mixed > fieldset > .wicfr-fields > .wicfr-field > .wicfr-input-label-container,.wicfr-field-inline_mixed > fieldset > .wicfr-fields > .wicfr-field > * > .wicfr-input-label-container{padding: 0;display: inline-block;width: 100%;}.wicfr-field-inline_mixed > fieldset > .wicfr-fields > .wicfr-field > .wicfr-input-label-container > label,.wicfr-field-inline_mixed > fieldset > .wicfr-fields > .wicfr-field > * > .wicfr-input-label-container > label{display: inline-block;}.wicfr-field-inline_mixed > fieldset > .wicfr-fields > .wicfr-field > .wicfr-input-label-container > label > input,.wicfr-field-inline_mixed > fieldset > .wicfr-fields > .wicfr-field > * > .wicfr-input-label-container > label > input{display: inline-block;min-width: 100%;margin-right: auto;margin-left: auto;}.wicfr-field-inline_mixed .wicfr-input-label-container,.wicfr-field-inline_mixed .wicfr-input-label-string{min-width: 0;}";
        }
    }
    